name: 'Publish Linux ARM Builds'

on:
  workflow_dispatch: # Manual trigger
  push:
    tags:
      - 'v*' # Trigger the workflow on version tags, e.g., v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest  # Using the latest Ubuntu environment

    strategy:
      matrix:
        arch: [aarch64, armv7l]  # ARM architectures to target
        include:
          - arch: aarch64
            deb: arm64
            rpm: aarch64
            appimage: aarch64
          - arch: armv7l
            deb: armhf
            rpm: arm
            appimage: armhf

    steps:
      - uses: actions/checkout@v4  # Checkout the code

      - name: Cache rust build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri
          cache-on-failure: true

      - name: Set up Rust environment
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl libssl-dev libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev patchelf libfuse2 file

      - name: Install frontend dependencies using npm
        run: |
          curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install

      - name: Build app
        run: |
          npm run tauri build -- --target ${{ matrix.arch }} --release

      - name: Get app version
        run: echo "APP_VERSION=$(jq -r .version src-tauri/tauri.conf.json)" >> $GITHUB_ENV

      - name: Create GitHub Release and Upload Artifacts
        id: create_release
        run: |
          TAG_NAME=${{ github.ref }}
          RELEASE_NAME="Release $TAG_NAME"
          BODY="Automated release from GitHub Actions."

          # Create a new GitHub release if it doesn't exist
          RELEASE=$(gh release view $TAG_NAME --json name -q ".name" || echo "null")

          if [ "$RELEASE" = "null" ]; then
            gh release create $TAG_NAME \
              src-tauri/target/release/bundle/deb/appname_${{ env.APP_VERSION }}_${{ matrix.deb }}.deb \
              src-tauri/target/release/bundle/rpm/appname-${{ env.APP_VERSION }}-1.${{ matrix.rpm }}.rpm \
              src-tauri/target/release/bundle/appimage/appname_${{ env.APP_VERSION }}_${{ matrix.appimage }}.AppImage \
              --title "$RELEASE_NAME" \
              --notes "$BODY"
          else
            echo "Release $TAG_NAME already exists. Skipping release creation."
          fi

      - name: Upload Deb bundle
        uses: actions/upload-artifact@v4
        with:
          name: Debian Bundle
          path: ${{ github.workspace }}/src-tauri/target/release/bundle/deb/appname_${{ env.APP_VERSION }}_${{ matrix.deb }}.deb

      - name: Upload RPM bundle
        uses: actions/upload-artifact@v4
        with:
          name: RPM Bundle
          path: ${{ github.workspace }}/src-tauri/target/release/bundle/rpm/appname-${{ env.APP_VERSION }}-1.${{ matrix.rpm }}.rpm

      - name: Upload AppImage bundle
        uses: actions/upload-artifact@v4
        with:
          name: AppImage Bundle
<<<<<<< HEAD
          path: ${{ github.workspace }}/src-tauri/target/release/bundle/appimage/appname_${{ env.APP_VERSION }}_${{ matrix.appimage }}.AppImage
=======
          path: ${{ github.workspace }}/src-tauri/target/release/bundle/appimage/appname_${{ env.APP_VERSION }}_${{ matrix.appimage }}.AppImage
>>>>>>> b6c6a7e24694c5bcac5592cd7d7aeb96e34605e3
